"""Add user scope columns

Revision ID: 355253857019
Revises: a68409b3d06c
Create Date: 2026-08-10 12:35:19.685803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '355253857019'
down_revision: Union[str, Sequence[str], None] = 'a68409b3d06c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('state_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('district_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_district_id'), 'users', ['district_id'], unique=False)
    op.create_index(op.f('ix_users_state_id'), 'users', ['state_id'], unique=False)
    op.create_foreign_key(None, 'users', 'states', ['state_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'districts', ['district_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_state_id'), table_name='users')
    op.drop_index(op.f('ix_users_district_id'), table_name='users')
    op.drop_column('users', 'district_id')
    op.drop_column('users', 'state_id')
    # ### end Alembic commands ###
