"""add_historical_rainfall

Revision ID: 4ada9482d8b8
Revises: 5dd41f6a994b
Create Date: 2026-08-17 00:21:11.637292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ada9482d8b8'
down_revision: Union[str, Sequence[str], None] = '5dd41f6a994b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_rainfall',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('original_district', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('avg_rainfall', sa.Double(), nullable=False),
    sa.Column('agency_name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_rainfall_date'), 'historical_rainfall', ['date'], unique=False)
    op.create_index(op.f('ix_historical_rainfall_district'), 'historical_rainfall', ['district'], unique=False)
    op.create_index(op.f('ix_historical_rainfall_month'), 'historical_rainfall', ['month'], unique=False)
    op.create_index(op.f('ix_historical_rainfall_year'), 'historical_rainfall', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_rainfall_year'), table_name='historical_rainfall')
    op.drop_index(op.f('ix_historical_rainfall_month'), table_name='historical_rainfall')
    op.drop_index(op.f('ix_historical_rainfall_district'), table_name='historical_rainfall')
    op.drop_index(op.f('ix_historical_rainfall_date'), table_name='historical_rainfall')
    op.drop_table('historical_rainfall')
    # ### end Alembic commands ###
