"""add_facilities_table

Revision ID: 5dd41f6a994b
Revises: 20230810_1405
Create Date: 2026-08-10 15:41:18.968597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dd41f6a994b'
down_revision: Union[str, Sequence[str], None] = '20230810_1405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('facility_type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('ward_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=150), nullable=True),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_city_id'), 'facilities', ['city_id'], unique=False)
    op.create_index(op.f('ix_facilities_district_id'), 'facilities', ['district_id'], unique=False)
    op.create_index(op.f('ix_facilities_state_id'), 'facilities', ['state_id'], unique=False)
    op.create_index(op.f('ix_facilities_ward_id'), 'facilities', ['ward_id'], unique=False)
    op.create_index(op.f('ix_facilities_zone_id'), 'facilities', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facilities_zone_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_ward_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_state_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_district_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_city_id'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
