import { 
  LayoutDashboard, 
  AlertTriangle, 
  TrendingUp,
  Map, 
  User, 
  Settings, 
  Bell, 
  LogOut, 
  ChevronRight, 
  ChevronLeft, 
  X, 
  Search, 
  Menu, 
  Phone, 
  Mail, 
  Plus, 
  Camera, 
  Mic, 
  MapPin, 
  Layers, 
  Filter, 
  Activity, 
  Send,
  CloudRain,
  Car,
  HeartPulse,
  Flame,
  Shield,
  FileText,
  Clock,
  CheckCircle,
  HelpCircle,
  AlertCircle
} from 'lucide-react'

// Export design aliases for unified layout referencing
export {
  LayoutDashboard as DashboardIcon,
  AlertTriangle as AlertIcon,
  TrendingUp as TrendIcon,
  Map as MapIcon,
  User as UserIcon,
  Settings as SettingsIcon,
  Bell as BellIcon,
  LogOut as LogoutIcon,
  ChevronRight as ChevronRightIcon,
  ChevronLeft as ChevronLeftIcon,
  X as CloseIcon,
  Search as SearchIcon,
  Menu as MenuIcon,
  Phone as PhoneIcon,
  Mail as MailIcon,
  Plus as PlusIcon,
  Camera as CameraIcon,
  Mic as MicIcon,
  MapPin as MapPinIcon,
  Layers as LayersIcon,
  Filter as FilterIcon,
  Activity as ActivityIcon,
  Send as SendIcon,
  CloudRain as WeatherIcon,
  Car as TrafficIcon,
  HeartPulse as HealthIcon,
  Flame as FireIcon,
  Shield as PoliceIcon,
  FileText as DocumentIcon,
  Clock as TimelineIcon,
  CheckCircle as SuccessIcon,
  HelpCircle as HelpIcon,
  AlertCircle as ErrorIcon
}
